# Dependencies
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    - tables
gems:
  - jekyll-redirect-from


# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            Biopython
tagline:          The Biopython Project
url:              http://biopython.org
#paginate:         1
baseurl:          /
author:
  name:           Biopython
  url:            https://twitter.com/biopython


# Custom vars
#hyde theme seems to use version as a GitHub tag...?
#version:          1.65
github:
  repo:           https://github.com/biopython/biopython

# Page settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
