# Dependencies
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    - tables
gems:
  - jekyll-redirect-from

# Setup
title: Biopython
baseurl: /

# Page settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
